FROM nginx:alpine

COPY index.html   /usr/share/nginx/html/index.html
COPY dashboard.js /usr/share/nginx/html/dashboard.js
COPY admin.html   /usr/share/nginx/html/admin.html
COPY nginx.conf   /etc/nginx/conf.d/default.conf

EXPOSE 80
